// Generated by CoffeeScript 1.6.2
$(function() {
  var head, script;

  $("#userNavigation").append("<li class=\"menuDivider\"></li>\n<li role=\"menuitem\"><a class=\"navSubmenu\" href=\"#\" onclick=\"return MathToggle(this)\" role=\"button\">Stop LaTeX rendering</a></li>");
  head = document.getElementsByTagName("head")[0];
  script = document.createElement("script");
  script.type = "text/x-mathjax-config";
  script[(window.opera ? "innerHTML" : "text")] = "MathJax.Hub.Config({\n  tex2jax: {\n    inlineMath: [[\"$\", \"$\"]],\n    displayMath: [[\"$$\", \"$$\"]]\n  }, showMathMenu: false\n});\n\nvar MathQueue = null\n\nvar MathEnable = function() {\n  MathQueue = setInterval(function() {\n    MathJax.Hub.queue.pending = 0\n    MathJax.Hub.Queue([\"Typeset\", MathJax.Hub])\n  }, 2000)\n}\n\nvar MathRevert = function() {\n  var HTML = MathJax.HTML\n    , jax = MathJax.Hub.getAllJax()\n\n  for (var i = 0, ii = jax.length; i < ii; i++) {\n    var script = jax[i].SourceElement()\n      , tex = jax[i].originalText\n\n    if (script.type.match(/display/))\n      tex = \"$$ \"+ tex +\" $$\"\n    else\n      tex = \"$\"+ tex +\"$\"\n\n    jax[i].Remove()\n\n    var preview = script.previousSibling\n    if (preview && preview.className === \"MathJax_Preview\")\n      preview.parentNode.removeChild(preview)\n\n    preview = HTML.Element(\"span\", {className: \"MathJax_Preview\"}, [tex])\n    script.parentNode.insertBefore(preview,script)\n  }\n\n  window.clearInterval(MathQueue)\n  MathJax.Hub.queue.pending = 1\n}\n\nvar MathText = \"\"\nvar MathToggle = function(el) {\n  console.log(el.innerHTML)\n  console.log(el.innerHTML == \"Stop LaTeX rendering\")\n  MathText = \"\"\n\n  if (el.innerHTML == \"Stop LaTeX rendering\") {\n    el.innerHTML = \"Running...\"\n    MathText = \"Start LaTeX rendering\"\n    MathRevert()\n\n    setTimeout(function() { el.innerHTML = MathText }, 1000)\n    return false\n  }\n  if (el.innerHTML == \"Start LaTeX rendering\") {\n    el.innerHTML = \"Running...\"\n    MathText = \"Stop LaTeX rendering\"\n    MathEnable()\n\n    setTimeout(function() { el.innerHTML = MathText }, 2000)\n    return false\n  }\n  return false\n}\n\nMathEnable()";
  head.appendChild(script);
  script = document.createElement("script");
  script.type = "text/javascript";
  script.src = "https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS_HTML";
  return head.appendChild(script);
});
